<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BDC6-DX-6GN5NK2" name="TestNGdemo.Softasert" tests="1" failures="1" timestamp="28 May 2019 07:27:14 GMT" time="0.016" errors="0">
  <testcase name="met1" time="0.016" classname="TestNGdemo.Softasert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Hell] but found [Hello]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hell] but found [Hello]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestNGdemo.Softasert.met1(Softasert.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- met1 -->
</testsuite> <!-- TestNGdemo.Softasert -->
